coverage:
  range: 50..100
  round: down
  precision: 0

  status:
    project: off
    patch: off
    changes: off

# https://docs.codecov.io/docs/pull-request-comments
comment:
  layout: "diff", #"diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: yes       # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches: null          # branch names that can post comment

ignore:
  - "*/testing.go"
